CREATE TABLE Users(
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	SURNAME VARCHAR(50) NOT NULL,
	DEPARTMENT_ID INT REFERENCES Department(ID) NOT NULL,
	SALARY INT NOT NULL DEFAULT(0) CHECK(SALARY>=0)
);